### ISSUE TITLE
porn link

### ISSUE THREAD

**Issue by bisqet** [rwaldron/idiomatic.js#229]
I read this repo and at the end(  https://github.com/rwaldron/idiomatic.js#everything-is-permitted-extending-built-ins-by-andrew-dupont-jsconf2011-portland-oregon  ) it have this link to porno site http://www.everytalk.tv/talks/441-JSConf-Everything-is-Permitted-Extending-Built-ins 
I reinforce this concept by watching a lot 😆

**Comment by StubberG3** [comment]
Was reading through the guide and noticed this too. You guys may want to fix this link. :)

**Comment by leobalter** [comment]
it seems like this has been resolved by 49dc598
