### ISSUE TITLE
TOC

### ISSUE THREAD

**Issue by ghost** [rwaldron/idiomatic.js#6]
Small thing but will be useful, especially as this grows. There needs to be a TOC linking to major sections using anchor links.

**Comment by FreakTheMighty** [comment]
It would be great if all the sections had anchor links. For example shouldn't "B. Assignments, Declarations, Functions ( Named, Expression, Constructor )" be a markdown header like `### B. Assignments, Declarations, Functions ( Named, Expression, Constructor )`
